Zgsj 31/feature/core banking setup
woorifisa-projects-3rd/first-team-MSA-BE pull request #3
Opened 2024-11-05 07:30 UTC by jihyuk0414

## 변경 사항
ENTITY 모두 생성 완료

## 테스트 코드를 작성하거나, 해당 기능등 들에 대해 모두 테스트를 진행했나요?
네

## 체크리스트
- [v] 코드 컨벤션을 준수하였는가?
- [v] 모든 테스트가 통과하는가?

## 기타 하고 싶은 말
준현님 전담 바랍니다

2024-11-05 07:47 UTC, my123dsa commented on core-bank/src/main/java/com/example/core_bank/core_bank/model/Account.java
> +
정적 팩토리 패턴 찾아서 작성해 보세요

2024-11-05 07:48 UTC, my123dsa commented on core-bank/src/main/java/com/example/core_bank/core_bank/model/Account.java
> +
cascade = CascadeType.REMOVE 가 뭔지 설명해 보세요

2024-11-05 07:58 UTC, my123dsa commented on core-bank/src/main/java/com/example/core_bank/core_bank/model/TransactionHistory.java
> +
cascade = CascadeType.REMOVE
취소

2024-11-05 08:16 UTC, my123dsa commented on core-bank/src/main/java/com/example/core_bank/core_bank/exception/GlobalExceptionHandler.java
> +
...

2024-11-05 08:16 UTC, my123dsa requested changes
해야해요

2024-11-05 08:46 UTC, jihyuk0414 commented on core-bank/src/main/java/com/example/core_bank/core_bank/model/Account.java
> +
변경했습니다

2024-11-05 08:46 UTC, jihyuk0414 commented
> 해야해요

변경했습니다

2024-11-05 08:46 UTC, jihyuk0414 commented on core-bank/src/main/java/com/example/core_bank/core_bank/model/TransactionHistory.java
> +
삭제했습니다!

2024-11-05 08:46 UTC, jihyuk0414 commented on core-bank/src/main/java/com/example/core_bank/core_bank/exception/GlobalExceptionHandler.java
> +
변경했습니다

2024-11-06 00:21 UTC, my123dsa approved these changes

2024-11-06 00:39 UTC, merged